from __future__ import annotations

import math
from pathlib import Path

import numpy as np


ROOT = Path(__file__).resolve().parent.parent
MODEL_PATH = ROOT / "models" / "basic_scene.xml"
ARUCO_TEXTURE_PATH = ROOT / "assets" / "aruco_board.png"

DRONE_CAMERA_NAME = "drone_cam"
DRONE_CAMERA_DOWN_ANGLE_DEG = 45.0
QUADCOPTER_BODY_NAME = "quadcopter"
ROOT_JOINT_NAME = "root"
ROTOR_SITE_NAMES = ("thrust_fl", "thrust_fr", "thrust_rl", "thrust_rr")

LANDING_CAR_BODY_NAME = "landing_car"
LANDING_CAR_X_JOINT_NAME = "landing_car_x"
LANDING_CAR_Y_JOINT_NAME = "landing_car_y"
LANDING_PLATFORM_GEOM_NAME = "landing_platform"

CAR_CIRCLE_CENTER = np.array([10.0, 0.0, 0.22])
CAR_CIRCLE_RADIUS = 2.2
CAR_LINEAR_SPEED = 1.1
CAR_STRAIGHT_START = np.array([12.2, 0.0, 0.22])
CAR_SINE_START = np.array([12.2, 0.0, 0.22])
CAR_SINE_AMPLITUDE = 2.0
CAR_SINE_WAVELENGTH = 8.0
CAR_POSITION_KP = 1.5
CAR_POSITION_KD = 2.5
CAR_MAX_FORCE = 20.0

ARUCO_MARKER_ID = 23
ARUCO_MARKER_LENGTH = 1.08
VISION_FPS = 12.0
VISION_WIDTH = 1280
VISION_HEIGHT = 720

ARM_LENGTH = 0.42
YAW_TORQUE_COEFF = 0.025
MAX_ROTOR_THRUST = 8.0
ALTITUDE_KP = 7.0
ALTITUDE_KD = 4.5
POSITION_KP = 0.8
POSITION_KD = 1.2
POSITION_KI = 0.05
MAX_POSITION_INTEGRAL = 3.0
MAX_TILT_TARGET = math.radians(45.0)
CAPTURE_POSITION_KP = 1.8
CAPTURE_POSITION_KD = 2.2
CAPTURE_MAX_TILT_TARGET = math.radians(35.0)
ATTITUDE_KP = 1.1
ATTITUDE_KD = 0.28
YAW_KP = 0.35
YAW_KD = 0.18
MAX_YAW_TORQUE = 0.06
YAW_ONLY_LEVEL_KP = 2.0
YAW_ONLY_LEVEL_KD = 0.7
YAW_TRAVEL_SPEED_THRESHOLD = 0.15
YAW_TARGET_RATE_LIMIT = math.radians(40.0)
YAW_PRIORITY_FULL_ERROR = math.radians(40.0)
YAW_PRIORITY_MIN_XY_SCALE = 0.08
CAPTURE_YAW_SOFT_LIMIT = math.radians(20.0)

WIND_FORCE_N = 0.6
WIND_CHANGE_INTERVAL = 4.0

LANDING_CLEARANCE = 0.35
LANDING_DESCENT_RATE = 0.45
CAPTURE_TRIGGER_XY_ERROR = 2.5
CAPTURE_TRIGGER_CLEARANCE = 2.5
CAPTURE_CLEARANCE = 0.12
CAPTURE_DESCENT_RATE = 1.2
CUTOFF_XY_ERROR = 0.35
CUTOFF_REL_SPEED = 0.5
CUTOFF_CLEARANCE = 0.22

APPROACH_BEHIND_DISTANCE = 3.0
APPROACH_BLEND_CLEARANCE = 3.0
IMAGE_CENTERING_GAIN = 0.9
MAX_IMAGE_CENTERING_OFFSET = 1.2

MPC_HORIZON_SECONDS = 1.6
MPC_REPLAN_INTERVAL = 0.08
MPC_PREDICTION_STEPS = 5
MPC_RESPONSE_TIME = 0.8
MPC_FOV_MARGIN = 0.72
MPC_FOV_PENALTY = 1200.0
MPC_LANDING_ERROR_WEIGHT = 1.0
MPC_APPROACH_ERROR_WEIGHT = 2.5
MPC_CONTROL_EFFORT_WEIGHT = 0.08
MPC_CLEARANCE_WEIGHT = 0.35
MPC_BEHIND_DISTANCES = (1.0, 2.5, 4.0, 6.0)
MPC_SIDE_OFFSETS = (-1.5, 0.0, 1.5)
MPC_CLEARANCES = (0.6, 1.4, 2.5, 4.0)
MPC_COMMIT_DISTANCE = 1.6
MPC_MIN_BEHIND_DISTANCE = 0.35
MPC_MIN_CLEARANCE = 0.45
MPC_GOOD_FOV_SLACK = 0.03
MPC_BAD_FOV_SLACK = -0.25
MPC_GOOD_IMAGE_EDGE = 0.58
MPC_BAD_IMAGE_EDGE = 0.88
MPC_APPROACH_PHASE_RATE = 0.18
MPC_RETREAT_PHASE_RATE = 0.45
MPC_TERMINAL_PROGRESS_WEIGHT = 3.0
MPC_PLOP_PHASE = 0.62
MPC_PLOP_XY_DISTANCE = 3.2
MPC_PLOP_LEAD_TIME = 0.35
MPC_PLOP_CLEARANCE = -0.06
MPC_PLOP_DESCENT_RATE = 2.0
MPC_PLOP_CUTOFF_XY_ERROR = 1.1
MPC_PLOP_CUTOFF_REL_SPEED = 1.4
MPC_PLOP_CUTOFF_CLEARANCE = 0.35
